---
title: "Personal Blog"
date: 2020-06-14
theme: minima
author: "Ryan Lin"
email: "rlin@ebnet.org"
description: > # this means to ignore newlines until "baseurl:"
 Played EBHS VB, volunteer at library, professional valorant player
# social links
twitter_username: @RealRlin # DO NOT include the @ character, or else the build will fail!
github_username:  egrenada # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
---
